SPEEDO_ROUTES = {
    "Route 1": {
        "from": "Railway Station",
        "to": "Bhatti Chowk",
        "stops": [
            "Railway Station",
            "Ek Moriya",
            "Nawaz Sharif Hospital",
            "Kashmiri Gate",
            "Lari Adda",
            "Azadi Chowk",
            "Texali Chowk",
            "Bhatti Chowk",
        ],
    },
    "Route 2": {
        "from": "Samanabad Mor",
        "to": "Bhatti Chowk",
        "stops": [
            "Samanabad Morr",
            "Corporation Chowk",
            "Taj Company",
            "Sanda",
            "Double Sarkan",
            "Moon Market",
            "Ganda Nala",
            "Bhatti Chowk",
        ],
    },
    "Route 3": {
        "from": "Railway Station",
        "to": "Shahdara Lari Adda",
        "stops": [
            "Railway Station",
            "Ek Moriya",
            "Nawaz Sharif Hospital",
            "Kashmiri Gate",
            "Lari Adda",
            "Azadi Chowk",
            "Timber Market",
            "METRO",
            "Niazi Chowk",
            "Shahdara Metro Station",
            "Shahdara Lari Adda",
        ],
    },
    "Route 4": {
        "from": "R.A Bazar",
        "to": "Chungi Amar Sidhu",
        "stops": [
            "R.A Bazar",
            "Nadeem Chowk",
            "Defence Morr",
            "Shareef Market",
            "Walton",
            "Qainchi",
            "Ghazi Chowk",
            "Chungi Amar Sidhu",
        ],
    },
    "Route 5": {
        "from": "Shad Bagh Underpass",
        "to": "Bhatti Chowk",
        "stops": [
            "Shad Bagh Underpass",
            "Rajput Park",
            "Madina Chowk",
            "Lohay Wali Pulley",
            "Badami Bagh",
            "Lari Adda Gol Chakar",
            "Azadi Chowk",
            "Taxali Chowk",
            "Bhatti Chowk",
        ],
    },
    "Route 6": {
        "from": "Babu Sabu",
        "to": "Raj Garh Chowk",
        "stops": [
            "Babu Sabu",
            "Niazi Adda",
            "City Bus Stand",
            "Chowk Yateem Khana",
            "Bhala Stop",
            "Samanabad Morr",
            "Chauburji",
            "Riwaz Garden",
            "M.A.O College",
            "Firdous Cinema",
            "Raj Garh Chowk",
        ],
    },
    "Route 7": {
        "from": "Bagrian",
        "to": "Chungi Amar Sidhu",
        "stops": [
            "Bagrian",
            "Depot Chowk",
            "Minhaj University",
            "Hamdard Chowk",
            "Rehmat Eye Hospital",
            "Pindi Stop",
            "Peco Morr",
            "Kot Lakhpat Railway Station",
            "Phatak Mandi",
            "Qainchi",
            "Ghazi Chowk",
            "Chungi Amar Sidhu",
        ],
    },
    "Route 8": {
        "from": "Doctor Hospital",
        "to": "Canal",
        "stops": [
            "Doctor Hospital",
            "Wafaqi Colony",
            "IBA Stop",
            "Hailey College",
            "Campus Pull",
            "Barkat Market",
            "Kalma Chowk",
            "Qaddafi Stadium",
            "Canal",
        ],
    },
    "Route 9": {
        "from": "Railway Station",
        "to": "Sham Nagar",
        "stops": [
            "Railway Station",
            "Haji Camp",
            "Shimla Pahari",
            "Lahore Zoo",
            "Chairing Cross",
            "Ganga Ram Hospital",
            "Qartaba Chowk",
            "Chauburji",
            "Sham Nagar",
        ],
    },
    "Route 10": {
        "from": "Multan Chungi",
        "to": "Qartaba Chowk",
        "stops": [
            "Multan Chungi",
            "Mustafa Town",
            "Karim Block Market",
            "PU Examination Center",
            "Bhekewal Morr",
            "Wahdat Colony",
            "Naqsha Stop",
            "Canal",
            "Ichra",
            "Shama",
            "Qartaba Chowk",
        ],
    },
    "Route 11": {
        "from": "Babu Sabu",
        "to": "Main Market Gulberg",
        "stops": [
            "Babu Sabu",
            "Niazi Adda",
            "City Bus Stand",
            "Chowk Yateem Khana",
            "Scheme Morr",
            "Flat Stop",
            "Dubai Chowk",
            "Bhekewal Morr",
            "Sheikh Zaid Hospital",
            "Campus Pull",
            "Barkat Market",
            "Kalma Chowk",
            "Liberty Chowk",
            "Hafeez Center",
            "Mini Market",
            "Main Market Gulberg",
        ],
    },
    "Route 12": {
        "from": "R.A Bazar",
        "to": "Civil Secretariat",
        "stops": [
            "R.A Bazar",
            "PAF Market",
            "Girja Chowk",
            "Afshan Chowk",
            "Fortress Stadium",
            "Gymkhana",
            "Aitchison College",
            "PC Hotel",
            "Lahore Zoo",
            "Chairing Cross",
            "GPO",
            "Anarkali",
            "Civil Secretariat",
        ],
    },
    "Route 13": {
        "from": "Bagrian",
        "to": "Kalma Chowk",
        "stops": [
            "Bagrian",
            "Ghazi Chowk",
            "UMT Stop",
            "Khokhar Chowk",
            "Akbar Chowk",
            "Pindi Stop",
            "Peco Morr",
            "Phatak Mandi",
            "Ittefaq Hospital",
            "Model Town",
            "Kalma Chowk",
        ],
    },
    "Route 14": {
        "from": "R.A Bazar",
        "to": "Chungi Amar Sidhu",
        "stops": [
            "R.A Bazar",
            "Fauji Foundation",
            "Ali View Garden",
            "Bhatta Chowk",
            "DHA Nursery",
            "LESCO",
            "Chota Ishara Stop",
            "Naka Stop",
            "Ghazi Chowk",
            "Chungi Amar Sidhu",
        ],
    },
    "Route 15": {
        "from": "Qartba Chowk",
        "to": "Babu Sabu",
        "stops": [
            "Qartba Chowk",
            "Hakeem M. Ajmal Khan Road",
            "Gulshan Ravi Road",
            "Kacha Ferozepur Road",
            "Babu Sabu",
        ],
    },
    "Route 16": {
        "from": "Railway Station",
        "to": "Bhatti Chowk",
        "stops": ["Railway Station", "Circular Road", "Ek Moriya", "Bhatti Chowk"],
    },
    "Route 17": {
        "from": "Canal",
        "to": "Railway Station",
        "stops": [
            "Canal",
            "Main Boulevard Shadman",
            "Davis Road",
            "Shimla Pahari",
            "Haji Camp",
            "Railway Station",
        ],
    },
    "Route 18": {
        "from": "Bhatti Chowk",
        "to": "Shimla Pahari",
        "stops": [
            "Bhatti Chowk",
            "Circular Road",
            "Nisbat Road",
            "Abbot Road",
            "Shimla Pahari",
        ],
    },
    "Route 19": {
        "from": "Main Market",
        "to": "Bhatti Chowk",
        "stops": [
            "Main Market",
            "Jail Road",
            "Lytton Road",
            "Crust Road",
            "Lower Mall Road",
            "Bhatti Chowk",
        ],
    },
    "Route 20": {
        "from": "Jain Mandar",
        "to": "Chowk Yateem Khana",
        "stops": [
            "Jain Mandar",
            "Al-Mumtaz Road",
            "Poonch Road",
            "Lake Road",
            "Chowk Yateem Khana",
        ],
    },
    "Route 21": {
        "from": "Depot Chowk",
        "to": "Thokar Niaz Baig",
        "stops": [
            "Depot Chowk",
            "Madar-e-Millat Road",
            "Ali Road",
            "Baig Road",
            "Canal Bank Road",
            "Thokar Niaz Baig",
        ],
    },
    "Route 22": {
        "from": "Depot Chowk",
        "to": "Thokar Niaz Baig",
        "stops": [
            "Depot Chowk",
            "Madar-e-Millat Road",
            "Sutlej Avenue",
            "Shahrah Nazria-e-Pakistan Avenue",
            "Thokar Niaz Baig",
        ],
    },
    "Route 23": {
        "from": "Valencia",
        "to": "Thokar Niaz Baig",
        "stops": [
            "Valencia",
            "Valencia Main Boulevard",
            "Khayaban-e-Jinnah",
            "Raiwind Road",
            "Thokar Niaz Baig",
        ],
    },
    "Route 24": {
        "from": "Multan Chungi",
        "to": "Ghazi Chowk",
        "stops": [
            "Multan Chungi",
            "College Road",
            "Maulana Shaukat Ali Road",
            "Wahdat Road",
            "Ghazi Chowk",
        ],
    },
    "Route 25": {
        "from": "R.A Bazar",
        "to": "Railway Station",
        "stops": [
            "R.A Bazar",
            "Lahore-Bedian Road",
            "Allama Iqbal Road",
            "Railway Station",
        ],
    },
    "Route 26": {
        "from": "R.A Bazar",
        "to": "Daroghawala",
        "stops": [
            "R.A Bazar",
            "G.T Road",
            "Shalimar Link Road",
            "Tufail Road",
            "Sarfraz Rafique Road",
            "Daroghawala",
        ],
    },
    "Route 27": {
        "from": "BataPur",
        "to": "Daroghawala",
        "stops": ["BataPur", "GT Road", "Daroghawala"],
    },
    "Route 28": {
        "from": "Quaid e Azam Interchange",
        "to": "Airport",
        "stops": [
            "Quaid e Azam Interchange",
            "Harbanspura Road",
            "Zarar Shaheed Road",
            "Airport",
        ],
    },
    "Route 29": {
        "from": "Niazi Interchange",
        "to": "Salamat Pura",
        "stops": [
            "Niazi Interchange",
            "Lahore Ring Road",
            "Band Road",
            "Sue Wala Road",
            "Salamat Pura",
        ],
    },
    "Route 30": {
        "from": "Daroghawala",
        "to": "Airport",
        "stops": ["Daroghawala", "G.T. Road", "Shalimar Link Road", "Airport"],
    },
    "Route 31": {
        "from": "Daroghawala",
        "to": "Lari Adda",
        "stops": [
            "Daroghawala",
            "Chamra Mandi",
            "Cooper Store",
            "UET",
            "Shalimar Chowk",
            "Lari Adda",
        ],
    },
    "Route 32": {
        "from": "Shimla Pahari",
        "to": "Ek Moriya",
        "stops": [
            "Shimla Pahari",
            "Durand Road",
            "Queen Mary Road",
            "Garhi Shahu Bridge",
            "Cooper Store",
            "Chamra Mandi",
            "Ek Moriya",
        ],
    },
    "Route 33": {
        "from": "Cooper Store",
        "to": "Mughalpura",
        "stops": ["Cooper Store", "Workshop Road", "Mughalpura Road", "Mughalpura"],
    },
    "Route 34": {
        "from": "Singhpura",
        "to": "Mughalpura",
        "stops": ["Singhpura", "Wheatman Road", "Griffin Road", "Mughalpura"],
    },
}
